skip_tags: true

configuration: Release

before_build:
  - nuget restore src\Caliburn.Dynamic.sln

cache:
  - src\packages -> **\packages.config

build:
  parallel: true
  project: src\Caliburn.Dynamic.sln

before_test:
  - ps: cd src\Caliburn.Dynamic.Tests\bin\Release

test_script:
  - nunit3-console Caliburn.Dynamic.Tests.dll --result=myresults.xml;format=AppVeyor

artifacts:
  - path: src\artifacts\*.nupkg